#!/usr/bin/env python3
"""Tests for reference/rule_gate.py, the PreToolUse gate that refuses a write whose path-scoped
rules are not in the calling agent's context. Stdlib unittest; run: python3 <this file>.

Hermetic: every case builds its own project, home directory, state directory, log and
transcripts under a temporary directory, and passes the environment to the gate explicitly, so
nothing reads or writes the operator's ~/.claude. The transcripts are synthetic but every entry
copies the shape Claude Code 2.1.286 wrote in the probe sessions (attachment entries, assistant
tool_use entries with `wireToolInputs`, user tool_result entries with and without
`toolUseResult`, the compact_boundary system entry and the compaction summary), with placeholder
paths.

  MATCHER      every glob x path pair in rule_gate_vectors.json, generated by the node-ignore
               bundled in Claude Code, replayed against the Python port; the vector file must
               cover every glob the kit ships, so a glob edit without a regeneration fails here;
               the places JavaScript's regex dialect differs from Python's
  FRONTMATTER  block lists quoted and not, a flow list, a comma string, braces, a trailing
               `/**`, a scalar on the next line, block scalars, a quoted key, and the shapes
               that make a rule unconditional (and so skipped)
  RULES        nested `.claude` directories, the user-scope exclusion, the project boundary,
               symlinked rule directories, a worktree nested in its repo, content dedupe
  COUNTING     each way a rule counts as loaded, each near miss that must not count, and a
               transcript line many read chunks long
  DECISION     the refusal and its inlined text, the size cap, the sibling window, the BLIND
               breaker, a stale pending entry after compaction, the kill switch, fail-open
  SAME RESPONSE  a result answering another call of the checked call's own response does not
               count, and a later call of that response is a sibling however long it waited
  ANOTHER HOOK  a refusal whose text another hook's refusal replaced is given again, never
               called a sibling or blind, until the breaker's limit
  DEFERRAL     a copy outside the project steps aside for the project's own wired copy, through
               settings.json or settings.local.json; it does not when that file is missing, the
               matcher leaves out the tool, the settings do not parse, or $CLAUDE_PROJECT_DIR is
               unset; the project's copy never steps aside
  END TO END   the hook as a subprocess: a refusal, then the same write allowed once the
               refusal's own text is in the transcript, and garbage on stdin still exiting 0

Every refusal has a negative control beside it: a gate only ever observed refusing is as unknown
as one only ever observed allowing.
"""
from __future__ import annotations

import hashlib
import importlib.util
import io
import json
import os
import subprocess
import sys
import tempfile
import time
import unittest
import unittest.mock as mock
import uuid
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
GATE_PATH = REPO / "reference" / "rule_gate.py"
VECTORS = Path(__file__).resolve().parent / "rule_gate_vectors.json"

_spec = importlib.util.spec_from_file_location("rule_gate", str(GATE_PATH))
assert _spec and _spec.loader
gate = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gate)

PY_RULE = ('---\npaths:\n  - "src/**/*.py"\n---\nRULE-SENTINEL-PY\n\n'
           'Every Python file carries # CANARY-PY.\n')
TEST_RULE = "---\npaths: [\"**/test_*.py\", '**/*_test.py']\n---\nRULE-SENTINEL-TEST\n"
ALWAYS_RULE = "RULE-SENTINEL-ALWAYS\n\nNo paths, so it loads at session start.\n"
DOC_RULE = '---\npaths:\n  - "docs/**"\n---\nRULE-SENTINEL-DOCS\n'
ANY_PY_RULE = '---\npaths:\n  - "**/*.py"\n---\nRULE-SENTINEL-ANY-PY\n'

# The prefix Claude Code 2.1.286 put in front of a JSON deny reason when it wrote the
# tool_result, measured in the deny probe. The gate must not depend on it, so the end-to-end
# case writes it the way it was measured.
DENY_PREFIX = "PreToolUse:Write hook error: "


class Transcript:
    """Appends entries in the shapes Claude Code writes, with placeholder ids and paths."""

    def __init__(self, path: Path, cwd: str, session: str, agent: str | None = None):
        self.path, self.cwd, self.session, self.agent = path, cwd, session, agent
        path.parent.mkdir(parents=True, exist_ok=True)
        path.touch()
        self.parent: str | None = None

    def _base(self, **fields) -> dict:
        e = {"parentUuid": self.parent, "isSidechain": self.agent is not None}
        if self.agent:
            e["agentId"] = self.agent
        e.update(fields)
        e.update({"uuid": str(uuid.uuid4()), "timestamp": "2026-10-01T03:10:24.369Z",
                  "userType": "external", "entrypoint": "sdk-cli", "cwd": self.cwd,
                  "sessionId": self.session, "version": "2.1.286", "gitBranch": "main"})
        self.parent = e["uuid"]
        return e

    def write(self, entry: dict) -> dict:
        with self.path.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry) + "\n")
        return entry

    def raw(self, text: str) -> None:
        with self.path.open("a", encoding="utf-8") as f:
            f.write(text)

    def user_prompt(self, text: str) -> dict:
        return self.write(self._base(type="user", message={"role": "user", "content": text}))

    def instructions(self, *paths: str) -> dict:
        files = [{"path": p, "type": "Project", "content": "..."} for p in paths]
        return self.write(self._base(type="attachment",
                                     attachment={"type": "instructions", "files": files},
                                     renderedRole="user"))

    def nested_memory(self, path: str) -> dict:
        content = {"path": path, "type": "Project", "content": "...", "globs": ["src/**/*.py"],
                   "contentDiffersFromDisk": True, "rawContent": "..."}
        return self.write(self._base(type="attachment", renderedRole="system", attachment={
            "type": "nested_memory", "path": path, "content": content,
            "displayPath": ".claude/rules/" + os.path.basename(path)}))

    def file_attachment(self, path: str, text: str) -> dict:
        n = text.count("\n") + 1
        return self.write(self._base(type="attachment", renderedRole="system", attachment={
            "type": "file", "filename": path,
            "content": {"type": "text", "file": {"filePath": path, "content": text,
                                                 "numLines": n, "startLine": 1, "totalLines": n}},
            "displayPath": os.path.basename(path)}))

    def tool_use(self, name: str, tool_input: dict, msg_id: str | None = None,
                 tid: str | None = None) -> str:
        """One tool call. Claude Code writes each call of a response as its own entry, all with
        the response's message.id, so calls of one response pass the same `msg_id`."""
        tid = tid or "toolu_" + uuid.uuid4().hex[:24]
        block = {"type": "tool_use", "id": tid, "name": name, "input": tool_input,
                 "caller": {"type": "direct"}}
        message = {"model": "claude-haiku-4-5-20251001",
                   "id": msg_id or "msg_" + uuid.uuid4().hex[:24],
                   "type": "message", "role": "assistant", "content": [block],
                   "stop_reason": "tool_use"}
        self.write(self._base(type="assistant", message=message, wireToolInputs={tid: tool_input},
                              requestId="req_" + uuid.uuid4().hex[:24]))
        return tid

    def tool_result(self, tid: str, content, tur=None, is_error: bool = False) -> dict:
        block = {"tool_use_id": tid, "type": "tool_result", "content": content}
        if is_error:
            block["is_error"] = True
        fields = {"type": "user", "message": {"role": "user", "content": [block]},
                  "promptId": str(uuid.uuid4())}
        if tur is not None:
            fields["toolUseResult"] = tur
        return self.write(self._base(**fields))

    def read(self, path: str, text: str, *, with_tur: bool = True, **extra) -> str:
        """A Read and its result. `extra` (offset, limit) makes it partial, as the tool would."""
        tid = self.tool_use("Read", {"file_path": path, **extra})
        lines = text.split("\n")
        start = int(extra.get("offset", 1))
        shown = lines[start - 1:start - 1 + int(extra.get("limit", len(lines)))]
        numbered = "\n".join(f"{start + i}\t{ln}" for i, ln in enumerate(shown))
        tur = {"type": "text", "file": {"filePath": path, "content": "\n".join(shown),
                                        "numLines": len(shown), "startLine": start,
                                        "totalLines": len(lines)}}
        self.tool_result(tid, numbered, tur if with_tur else None)
        return tid

    def read_unchanged(self, path: str, *, with_tur: bool = True) -> str:
        tid = self.tool_use("Read", {"file_path": path})
        tur = {"type": "file_unchanged", "file": {"filePath": path}}
        self.tool_result(tid, "Wasted call — file unchanged since your last Read. Refer to "
                         "that earlier tool_result instead.", tur if with_tur else None)
        return tid

    def boundary(self) -> dict:
        e = self._base(type="system", subtype="compact_boundary", content="Conversation compacted",
                       isMeta=False, level="info",
                       compactMetadata={"trigger": "manual", "preTokens": 25741,
                                        "postTokens": 3001})
        e["parentUuid"] = None
        return self.write(e)

    def summary(self, text: str) -> dict:
        return self.write(self._base(
            type="user", isVisibleInTranscriptOnly=True, isCompactSummary=True,
            message={"role": "user", "content": "This session is being continued from a "
                     "previous conversation that ran out of context.\n\nSummary:\n" + text}))

    def denied(self, tid: str, reason: str) -> dict:
        """A refused tool call's result, in the measured shape."""
        return self.tool_result(tid, DENY_PREFIX + reason, "Error: " + DENY_PREFIX + reason,
                                is_error=True)


class GateCase(unittest.TestCase):
    """A project with one path rule and one unconditional rule, a home, and a transcript."""

    def setUp(self):
        self._td = tempfile.TemporaryDirectory()
        self.root = Path(self._td.name).resolve()
        self.home = self.root / "home"
        self.proj = self.root / "proj"
        self.rules = self.proj / ".claude" / "rules"
        self.rules.mkdir(parents=True)
        (self.proj / "src").mkdir()
        self.py_rule = self.rules / "py.md"
        self.py_rule.write_text(PY_RULE)
        (self.rules / "always.md").write_text(ALWAYS_RULE)
        (self.proj / "src" / "a.py").write_text("def add(x, y):\n    return x + y\n")
        self.session = str(uuid.uuid4())
        self.tpath = (self.home / ".claude" / "projects" / "-placeholder-proj"
                      / (self.session + ".jsonl"))
        self.t = Transcript(self.tpath, str(self.proj), self.session)
        self.t.instructions(str(self.home / ".claude" / "CLAUDE.md"), str(self.rules / "always.md"))
        self.t.user_prompt("create src/b.py")
        self.log = self.root / "rule-gate.log"
        self.state = self.root / "state"
        self.env = {"HOME": str(self.home), "CLAUDE_PROJECT_DIR": str(self.proj),
                    "DISCIPLINE_RULE_GATE_LOG": str(self.log),
                    "DISCIPLINE_RULE_GATE_STATE": str(self.state)}
        self.now = 1_800_000_000.0

    def tearDown(self):
        self._td.cleanup()

    def hook_input(self, target=None, tool="Write", agent=None, tid=None, **tool_input) -> dict:
        target = str(self.proj / "src" / "b.py") if target is None else target
        key = "notebook_path" if tool == "NotebookEdit" else "file_path"
        d = {"session_id": self.session, "transcript_path": str(self.tpath), "cwd": str(self.proj),
             "prompt_id": str(uuid.uuid4()), "permission_mode": "bypassPermissions",
             "hook_event_name": "PreToolUse", "tool_name": tool,
             "tool_input": {key: target, "content": "def mul(x, y):\n    return x * y\n",
                            **tool_input},
             "tool_use_id": tid or "toolu_" + uuid.uuid4().hex[:24]}
        if agent:
            d.update({"agent_id": agent, "agent_type": "general-purpose"})
        return d

    def decide(self, hook_input=None, now=None, **env):
        return gate.decide(hook_input or self.hook_input(), {**self.env, **env},
                           self.now if now is None else now)

    def assertDenied(self, out) -> str:
        self.assertIsNotNone(out, "want a refusal, got a silent allow")
        hso = out["hookSpecificOutput"]
        self.assertEqual(hso.get("permissionDecision"), "deny", out)
        return hso["permissionDecisionReason"]

    def assertAllowedSilently(self, out):
        self.assertIsNone(out, f"want a silent allow, got {out}")

    def assertAllowedWithWarning(self, out) -> str:
        self.assertIsNotNone(out, "want an allow with a warning, got a silent allow")
        hso = out["hookSpecificOutput"]
        self.assertNotIn("permissionDecision", hso,
                         "an allow must leave the decision to the permission system")
        self.assertTrue(hso.get("additionalContext"), out)
        return hso["additionalContext"]

    def log_lines(self) -> list[str]:
        return self.log.read_text().splitlines() if self.log.exists() else []


# --- matcher -------------------------------------------------------------------------------------

class GoldenVectors(unittest.TestCase):
    """The Python port against the node-ignore that Claude Code bundles."""

    @classmethod
    def setUpClass(cls):
        cls.v = json.loads(VECTORS.read_text())

    def test_every_single_glob_vector(self):
        bad, n = [], 0
        for g in self.v["globs"]:
            want = set(self.v["matches"][g])
            norm = gate.normalize_globs([g])
            self.assertIsNotNone(norm, f"vector glob {g!r} normalizes to unconditional")
            for i, p in enumerate(self.v["paths"]):
                n += 1
                if gate.match(norm, p) != (i in want):
                    bad.append((g, p, i in want))
        self.assertGreater(n, 9000, "the vector file shrank; regenerate it rather than trim it")
        self.assertEqual(bad, [], f"{len(bad)} of {n} pairs disagree with node-ignore")

    def test_every_multi_glob_set(self):
        for s in self.v["sets"]:
            with self.subTest(s=s):
                self.assertEqual(gate.match(gate.normalize_globs(s["globs"]), s["path"]),
                                 s["match"])

    def test_vectors_cover_every_shipped_glob(self):
        """A glob edited in a rule without regenerating the vectors is unpinned. Fail instead."""
        shipped = set()
        for f in sorted((REPO / "claude-project" / "rules").glob("*.md")):
            shipped.update(gate.split_paths_value(gate.raw_paths(f.read_text()) or []))
        self.assertTrue(shipped, "no shipped globs read; the check would pass having read nothing")
        missing = sorted(shipped - set(self.v["globs"]))
        self.assertEqual(missing, [], "regenerate rule_gate_vectors.json for these globs")

    def test_provenance_names_the_source_and_the_generator(self):
        """Private paths in the file are the scrub gate's to catch; it scans every file."""
        self.assertIn("node-ignore bundled in Claude Code 2.1.286", self.v["provenance"])
        self.assertTrue(self.v["generator"] and self.v["command"])
        self.assertIn("ignore_bundled.cjs", "\n".join(self.v["generator"]))

    def test_provenance_says_how_to_recreate_the_matcher_the_generator_needs(self):
        """A generator that needs a file nobody can make is not a regeneration step."""
        for how in ("npm pack ignore@7.0.5", 'Symbol.for("setupWindows")'):
            self.assertIn(how, self.v["provenance"])

    def test_vectors_include_the_named_paths(self):
        for p in ("docs/adrs/ADR-0001-x.md", "stories/STORY-0001-x.md", "x/tests/a.py",
                  "packs/x/scripts/a.sh", "project/plugins.sbt", "../out.py", "latest.md"):
            self.assertIn(p, self.v["paths"])


class Matcher(unittest.TestCase):
    def test_case_insensitive(self):
        self.assertTrue(gate.match(["**/*.py"], "SRC/A.PY"))

    def test_star_does_not_cross_slash_and_double_star_does(self):
        self.assertFalse(gate.match(["src/*.py"], "src/sub/a.py"))
        self.assertTrue(gate.match(["src/**/*.py"], "src/sub/deep/a.py"))

    def test_a_pattern_with_a_slash_is_anchored_and_one_without_is_not(self):
        self.assertFalse(gate.match(["scripts/*.py"], "x/scripts/a.py"))
        self.assertTrue(gate.match(["README.md"], "sub/README.md"))

    def test_a_directory_pattern_matches_every_file_under_it(self):
        self.assertTrue(gate.match(["tests"], "pkg/tests/sub/a.py"))

    def test_parent_relative_and_absolute_paths_never_match(self):
        for p in ("../out.py", "..x/a.py", "/abs/a.py", "./a.py", ""):
            self.assertFalse(gate.match(["**/*.py", "**"], p), p)

    def test_javascript_regex_dialect_where_python_reads_it_differently(self):
        """node-ignore builds JavaScript regex source. Each expectation is node-ignore's answer,
        and the golden vectors pin the same globs."""
        self.assertTrue(gate.match(["\\a*"], "a"), "JavaScript reads \\a as the letter a; "
                        "Python reads it as BEL")
        self.assertTrue(gate.match(["\\p*"], "p"), "Python refuses \\p and the glob was dropped")
        self.assertTrue(gate.match(["\\e"], "e"))
        self.assertFalse(gate.match(["([] -[a-c]"], "+/(B"), "[] is an empty class in JavaScript")
        self.assertTrue(gate.match(["**/[/b["], "B"), "a [ inside a class is a plain character")


# --- frontmatter ---------------------------------------------------------------------------------

class Frontmatter(unittest.TestCase):
    def parse(self, fm: str):
        return gate.parse_paths_frontmatter(f"---\n{fm}\n---\nbody\n")

    def test_block_list_quoted_and_unquoted(self):
        self.assertEqual(self.parse('paths:\n  - "src/**/*.py"\n  - tests/*.py\n  - \'a.md\''),
                         ["src/**/*.py", "tests/*.py", "a.md"])

    def test_block_list_at_column_zero_with_comments(self):
        fm = "paths:\n- src/*.py  # the sources\n# a note\n- b.md\nother: 1"
        self.assertEqual(self.parse(fm), ["src/*.py", "b.md"])

    def test_flow_list(self):
        self.assertEqual(self.parse('paths: ["**/*.ts", \'**/*.tsx\', docs/*.md]'),
                         ["**/*.ts", "**/*.tsx", "docs/*.md"])

    def test_comma_string_plain_and_quoted(self):
        self.assertEqual(self.parse("paths: src/*.py, tests/*.py"), ["src/*.py", "tests/*.py"])
        self.assertEqual(self.parse('paths: "src/*.py, docs/**"'), ["src/*.py", "docs"])

    def test_braces_expand_and_commas_inside_braces_do_not_split(self):
        self.assertEqual(sorted(self.parse('paths: "src/**/*.{ts,tsx}, lib/*.js"')),
                         ["lib/*.js", "src/**/*.ts", "src/**/*.tsx"])
        self.assertEqual(sorted(self.parse('paths:\n  - "{a,b}/{c,d}.py"')),
                         ["a/c.py", "a/d.py", "b/c.py", "b/d.py"])

    def test_one_trailing_double_star_is_stripped(self):
        self.assertEqual(self.parse('paths:\n  - "docs/**"\n  - "x/**/**"'), ["docs", "x/**"])

    def test_a_scalar_on_the_lines_after_the_key(self):
        self.assertEqual(self.parse('paths:\n  "**/*.py"'), ["**/*.py"])
        self.assertEqual(self.parse("paths:\n  src/*.py,\n  docs/**\nother: 1"), ["src/*.py", "docs"])

    def test_block_scalars_folded_and_literal(self):
        self.assertEqual(self.parse("paths: >-\n  **/*.py,\n  **/*.go"), ["**/*.py", "**/*.go"],
                         "the old parser read the indicator >- as the glob")
        self.assertEqual(self.parse("paths: |\n  **/*.py, **/*.go\n"), ["**/*.py", "**/*.go"])
        self.assertIsNone(self.parse("paths: >\n"), "an empty block scalar is no paths at all")

    def test_a_quoted_key(self):
        self.assertEqual(self.parse('"paths":\n  - "**/*.py"'), ["**/*.py"])
        self.assertEqual(self.parse("'paths': src/*.py"), ["src/*.py"])

    def test_crlf_frontmatter(self):
        text = '---\r\npaths:\r\n  - "src/*.py"\r\n---\r\nbody\r\n'
        self.assertEqual(gate.parse_paths_frontmatter(text), ["src/*.py"])

    def test_unconditional_shapes_are_none(self):
        self.assertIsNone(gate.parse_paths_frontmatter("# no frontmatter at all\n"))
        self.assertIsNone(self.parse("description: no paths key"))
        self.assertIsNone(self.parse("paths:"))
        self.assertIsNone(self.parse("paths: []"))
        self.assertIsNone(self.parse('paths:\n  - "**"\n  - "**/**"'))
        self.assertEqual(gate.raw_paths("---\npaths:\n---\n"), [],
                         "an empty value is a declared key, which the coverage check reports")


# --- which rules apply ---------------------------------------------------------------------------

class ApplicableRules(GateCase):
    def names(self, target, root=None, home=None):
        return [os.path.relpath(r.path, self.root) for r in gate.applicable_rules(
            str(target), str(root or self.proj), str(home or self.home))]

    def test_matching_rule_found_and_unconditional_skipped(self):
        self.assertEqual(self.names(self.proj / "src" / "b.py"), ["proj/.claude/rules/py.md"])
        self.assertEqual(self.names(self.proj / "README.md"), [])

    def test_a_nested_claude_dir_matches_relative_to_its_own_directory(self):
        sub = self.proj / "pkg"
        (sub / ".claude" / "rules").mkdir(parents=True)
        (sub / ".claude" / "rules" / "docs.md").write_text(DOC_RULE)
        self.assertEqual(self.names(sub / "docs" / "x.md"), ["proj/pkg/.claude/rules/docs.md"])
        self.assertEqual(self.names(self.proj / "docs" / "x.md"), [])
        self.assertEqual(self.names(sub / "src" / "a.py"), [],
                         "src/**/*.py is anchored at proj, so pkg/src/a.py does not match it")

    def test_rules_in_subdirectories_of_rules_are_found(self):
        (self.rules / "lang").mkdir()
        (self.rules / "lang" / "test.md").write_text(TEST_RULE)
        self.assertEqual(sorted(self.names(self.proj / "src" / "test_a.py")),
                         ["proj/.claude/rules/lang/test.md", "proj/.claude/rules/py.md"])

    def test_user_scope_rules_are_excluded(self):
        user = self.home / ".claude" / "rules"
        user.mkdir(parents=True)
        (user / "everything.md").write_text('---\npaths:\n  - "**/*.py"\n---\nUSER\n')
        inside = self.home / "work" / "a.py"
        self.assertEqual(self.names(inside, root=self.home), [])
        self.assertEqual(self.names(inside, root=self.home, home=self.root / "elsewhere"),
                         ["home/.claude/rules/everything.md"], "negative control")

    def test_a_target_outside_the_project_gets_no_rules(self):
        other = self.root / "other"
        (other / ".claude" / "rules").mkdir(parents=True)
        (other / ".claude" / "rules" / "py.md").write_text(PY_RULE)
        self.assertEqual(self.names(other / "src" / "b.py"), [])
        self.assertEqual(self.names(other / "src" / "b.py", root=other),
                         ["other/.claude/rules/py.md"], "negative control")

    def test_a_symlinked_rules_subdirectory_inside_the_project_is_followed(self):
        shared = self.proj / "tools" / "rules"
        shared.mkdir(parents=True)
        (shared / "test.md").write_text(TEST_RULE)
        (self.rules / "shared").symlink_to(Path("..", "..", "tools", "rules"))
        self.assertIn("proj/.claude/rules/shared/test.md",
                      self.names(self.proj / "src" / "test_a.py"))

    def test_a_symlink_that_leaves_the_project_is_skipped_and_a_cycle_ends(self):
        outside = self.root / "outside"
        outside.mkdir()
        (outside / "test.md").write_text(TEST_RULE)
        (self.rules / "ext").symlink_to(outside)
        (self.rules / "ext-file.md").symlink_to(outside / "test.md")
        (self.rules / "loop").symlink_to(self.rules)
        self.assertEqual(self.names(self.proj / "src" / "test_a.py"),
                         ["proj/.claude/rules/py.md"], "Claude Code skips a link out of the project")
        wider = self.names(self.proj / "src" / "test_a.py", root=self.root)
        self.assertEqual(len(wider), 2, "negative control: inside a wider project root the "
                         f"links are followed (two links to one file count once): {wider}")

    def nested_worktree(self) -> Path:
        """The layout `git worktree add .claude/worktrees/wt` leaves, without running git."""
        wt = self.proj / ".claude" / "worktrees" / "wt"
        admin = self.proj / ".git" / "worktrees" / "wt"
        admin.mkdir(parents=True)
        (admin / "commondir").write_text("../..\n")
        (wt / ".claude" / "rules").mkdir(parents=True)
        (wt / ".git").write_text(f"gitdir: {admin}\n")
        (wt / ".claude" / "rules" / "py.md").write_text(ANY_PY_RULE + "worktree edit\n")
        (self.rules / "any.md").write_text(ANY_PY_RULE)
        return wt

    def test_a_worktree_nested_in_its_repo_does_not_get_the_main_checkouts_rules(self):
        wt = self.nested_worktree()
        target = wt / "src" / "b.py"
        self.assertEqual(self.names(target, root=wt),
                         ["proj/.claude/worktrees/wt/.claude/rules/py.md"])
        (wt / ".git").unlink()
        self.assertEqual(sorted(self.names(target, root=wt)),
                         ["proj/.claude/rules/any.md",
                          "proj/.claude/worktrees/wt/.claude/rules/py.md"],
                         "negative control: a plain nested directory walks up into proj")

    def test_two_copies_of_one_rule_count_once(self):
        sub = self.proj / "src"
        (sub / ".claude" / "rules").mkdir(parents=True)
        (sub / ".claude" / "rules" / "copy.md").write_text('---\npaths:\n  - "**/*.py"\n---\nC\n')
        (self.rules / "copy.md").write_text('---\npaths:\n  - "**/*.py"\n---\nC\n')
        self.assertEqual(len(self.names(sub / "b.py")), 2, "py.md and one copy of copy.md")


# --- what counts as loaded -----------------------------------------------------------------------

class Counting(GateCase):
    def loaded(self):
        lines, _ = gate.window_lines(str(self.tpath))
        return gate.loaded_rules(lines)

    def rule(self) -> str:
        return str(self.py_rule)

    def test_nested_memory_counts(self):
        self.t.read(str(self.proj / "src" / "a.py"), "def add(): ...")
        self.t.nested_memory(self.rule())
        self.assertIn(self.rule(), self.loaded().paths)

    def test_instructions_and_file_attachments_count(self):
        self.t.file_attachment(self.rule(), PY_RULE)
        got = self.loaded().paths
        self.assertIn(self.rule(), got)
        self.assertIn(str(self.rules / "always.md"), got)

    def test_full_read_counts_with_and_without_tool_use_result(self):
        self.t.read(self.rule(), PY_RULE)
        self.assertIn(self.rule(), self.loaded().paths)
        self.tpath.write_text("")
        self.t.read(self.rule(), PY_RULE, with_tur=False)
        self.assertIn(self.rule(), self.loaded().paths, "the subagent shape has no toolUseResult")

    def test_partial_read_does_not_count(self):
        self.t.read(self.rule(), PY_RULE, offset=5, limit=2)
        self.t.read(self.rule(), PY_RULE, with_tur=False, limit=3)
        self.assertNotIn(self.rule(), self.loaded().paths)

    def test_a_result_that_reports_a_partial_file_does_not_count(self):
        tid = self.t.tool_use("Read", {"file_path": self.rule()})
        self.t.tool_result(tid, "5\tRULE-SENTINEL-PY", {"type": "text", "file": {
            "filePath": self.rule(), "content": "x", "numLines": 2, "startLine": 5,
            "totalLines": 10}})
        self.assertNotIn(self.rule(), self.loaded().paths)

    def test_an_errored_read_and_an_unanswered_read_do_not_count(self):
        tid = self.t.tool_use("Read", {"file_path": self.rule()})
        self.t.tool_result(tid, "<tool_use_error>File does not exist.</tool_use_error>",
                           "Error: File does not exist.", is_error=True)
        self.t.tool_use("Read", {"file_path": self.rule()})
        self.assertNotIn(self.rule(), self.loaded().paths)

    def test_file_unchanged_counts_only_after_a_prior_load(self):
        self.t.read_unchanged(self.rule())
        self.t.read_unchanged(self.rule(), with_tur=False)
        self.assertNotIn(self.rule(), self.loaded().paths, "a stub alone proves nothing")
        self.t.read(self.rule(), PY_RULE)
        self.t.read_unchanged(self.rule())
        self.assertIn(self.rule(), self.loaded().paths)

    def test_compaction_summary_text_does_not_count(self):
        self.t.boundary()
        sha = hashlib.sha256(PY_RULE.encode()).hexdigest()
        self.t.summary(f"The user loaded {self.rule()}:\nrule-gate: inlined sha256={sha} "
                       f"path={self.rule()}\n{PY_RULE}")
        got = self.loaded()
        self.assertNotIn(self.rule(), got.paths)
        self.assertNotIn(sha, got.shas)

    def test_loads_before_the_last_boundary_do_not_count(self):
        self.t.nested_memory(self.rule())
        self.t.read(self.rule(), PY_RULE)
        self.t.boundary()
        self.t.summary("earlier work")
        self.t.boundary()
        self.t.instructions(str(self.rules / "always.md"))
        self.assertEqual(self.loaded().paths, {str(self.rules / "always.md")})
        whole = gate.loaded_rules(self.tpath.read_text().splitlines())
        self.assertNotIn(self.rule(), whole.paths, "a boundary inside the lines resets them too")

    def test_the_gates_own_inlined_text_counts_by_sha(self):
        tid = self.t.tool_use("Write", {"file_path": str(self.proj / "src" / "b.py")})
        sha = hashlib.sha256(PY_RULE.encode()).hexdigest()
        self.t.denied(tid, f"refused.\n\nrule-gate: inlined sha256={sha} path={self.rule()}\n"
                           f"{PY_RULE}\n\nretry")
        got = self.loaded()
        self.assertIn(sha, got.shas)
        self.assertNotIn(self.rule(), got.paths, "the marker counts the content, not the path")

    def test_tool_result_content_as_a_list_of_text_blocks(self):
        tid = self.t.tool_use("Read", {"file_path": self.rule()})
        self.t.tool_result(tid, [{"type": "text", "text": "1\t---"}])
        self.assertIn(self.rule(), self.loaded().paths)

    def test_reverse_chunked_read_matches_a_forward_read_across_utf8(self):
        self.t.user_prompt("café — \U0001f600 " * 50)
        self.t.boundary()
        for i in range(30):
            self.t.user_prompt(f"prompt {i} éè—\U0001f600")
            self.t.read(self.rule(), PY_RULE)
        forward = self.tpath.read_bytes().split(b"\n")
        cut = max(i for i, ln in enumerate(forward) if b"compact_boundary" in ln)
        want = [ln for ln in forward[cut + 1:]]
        for chunk in (1, 7, 64, 4096, 1 << 20):
            got, bid = gate.window_lines(str(self.tpath), chunk=chunk)
            self.assertEqual([g for g in got if g], [w for w in want if w], f"chunk={chunk}")
            self.assertTrue(bid)

    def test_a_line_many_chunks_long_is_read_in_linear_time(self):
        """Re-joining the partial line on every chunk copied N squared bytes: an 8 MB line took
        5.5 s at 4 KB chunks. Collecting the pieces and joining once takes milliseconds."""
        self.tpath.write_bytes(b'{"x": "' + b"a" * (8 << 20) + b'"}\n{"y": 1}\n')
        started = time.monotonic()
        got, _ = gate.window_lines(str(self.tpath), chunk=4096)
        took = time.monotonic() - started
        self.assertEqual([len(g) for g in got], [(8 << 20) + 9, 8, 0])
        self.assertLess(took, 1.0, f"window_lines took {took:.2f}s on one 8 MB line")

    def test_garbage_raises_unreadable(self):
        with self.assertRaises(gate.TranscriptUnreadable):
            gate.loaded_rules([b"\x00\xff garbage", b"not json {"])


class TranscriptSelection(GateCase):
    def test_main_thread_reads_transcript_path(self):
        self.assertEqual(gate.transcript_for(self.hook_input()), str(self.tpath))

    def test_subagent_reads_its_own_file_at_any_depth(self):
        base = self.tpath.with_suffix("")
        flat = base / "subagents" / "agent-a1.jsonl"
        nested = base / "subagents" / "workflows" / "wf_x" / "agent-b2.jsonl"
        for p in (flat, nested):
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text("")
        self.assertEqual(gate.transcript_for(self.hook_input(agent="a1")), str(flat))
        self.assertEqual(gate.transcript_for(self.hook_input(agent="b2")), str(nested))
        self.assertIsNone(gate.transcript_for(self.hook_input(agent="zz")))

    def test_a_subagent_does_not_inherit_the_parents_loads(self):
        self.t.nested_memory(str(self.py_rule))
        self.assertAllowedSilently(self.decide())
        sub = Transcript(self.tpath.with_suffix("") / "subagents" / "agent-s1.jsonl",
                         str(self.proj), self.session, agent="s1")
        sub.user_prompt("create src/b.py")
        reason = self.assertDenied(self.decide(self.hook_input(agent="s1")))
        self.assertIn("RULE-SENTINEL-PY", reason)
        sub.nested_memory(str(self.py_rule))
        self.assertAllowedSilently(self.decide(self.hook_input(agent="s1")))

    def test_a_missing_subagent_transcript_fails_open_and_logs(self):
        msg = self.assertAllowedWithWarning(self.decide(self.hook_input(agent="ghost")))
        self.assertIn("could not check", msg)
        self.assertTrue(any("\tFAIL-OPEN\t" in ln and "ghost" in ln for ln in self.log_lines()))


# --- the decision --------------------------------------------------------------------------------

class Decision(GateCase):
    def test_deny_inlines_the_full_text_after_the_marker_and_ends_with_the_retry_line(self):
        reason = self.assertDenied(self.decide())
        sha = hashlib.sha256(PY_RULE.encode()).hexdigest()
        marker = f"rule-gate: inlined sha256={sha} path={self.py_rule}"
        self.assertIn(marker + "\n" + PY_RULE.rstrip("\n"), reason)
        self.assertTrue(reason.endswith(gate.RETRY_LINE), reason[-200:])
        self.assertNotIn("RULE-SENTINEL-ALWAYS", reason, "the unconditional rule is not inlined")
        self.assertTrue(any("\tDENY\t" in ln for ln in self.log_lines()))

    def test_a_loaded_rule_is_allowed_silently(self):
        self.t.read(str(self.proj / "src" / "a.py"), "def add(): ...")
        self.t.nested_memory(str(self.py_rule))
        self.assertAllowedSilently(self.decide())

    def test_a_copy_of_the_rule_loaded_elsewhere_counts_by_content(self):
        copy = self.root / "worktree" / ".claude" / "rules" / "py.md"
        copy.parent.mkdir(parents=True)
        copy.write_text(PY_RULE)
        self.t.read(str(copy), PY_RULE)
        self.assertAllowedSilently(self.decide())
        copy.write_text(PY_RULE + "edited\n")
        self.assertDenied(self.decide(now=self.now + 1))

    def test_outside_project_and_unmatched_targets_are_allowed_silently(self):
        other = self.root / "else"
        (other / ".claude" / "rules").mkdir(parents=True)
        (other / ".claude" / "rules" / "py.md").write_text(PY_RULE)
        self.assertAllowedSilently(self.decide(self.hook_input(str(other / "src" / "b.py"))))
        self.assertAllowedSilently(self.decide(self.hook_input(str(self.proj / "notes.txt"))))
        self.assertEqual(self.log_lines(), [])

    def test_project_root_falls_back_to_cwd(self):
        env = dict(self.env)
        del env["CLAUDE_PROJECT_DIR"]
        self.assertDenied(gate.decide(self.hook_input(), env, self.now))

    def test_relative_target_resolves_against_cwd(self):
        self.assertDenied(self.decide(self.hook_input("src/b.py")))

    def test_edit_multiedit_and_notebookedit_are_gated(self):
        for tool in ("Edit", "MultiEdit", "NotebookEdit"):
            with self.subTest(tool=tool):
                d = self.hook_input(tool=tool)
                d["session_id"] = "session-for-" + tool
                self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.decide(d)))

    def test_non_gated_tools_are_silent(self):
        for tool in ("Read", "Bash", "Agent", "Glob"):
            d = self.hook_input()
            d["tool_name"] = tool
            self.assertAllowedSilently(self.decide(d))
        self.assertEqual(self.log_lines(), [])

    def test_kill_switch(self):
        self.assertAllowedSilently(self.decide(DISCIPLINE_RULE_GATE="off"))
        self.assertDenied(self.decide(DISCIPLINE_RULE_GATE="on"))

    def test_garbage_transcript_fails_open_with_a_log_line(self):
        self.tpath.write_bytes(b"\x00\x01 not a transcript\n{{{ also not\n")
        msg = self.assertAllowedWithWarning(self.decide())
        self.assertIn("transcript unreadable", msg)
        self.assertTrue(any("\tFAIL-OPEN\t" in ln for ln in self.log_lines()))

    def test_missing_transcript_and_unknown_shape_fail_open(self):
        self.tpath.unlink()
        self.assertAllowedWithWarning(self.decide())
        d = self.hook_input()
        d["tool_input"] = {"content": "no path"}
        self.assertAllowedWithWarning(self.decide(d))
        self.assertEqual(sum("\tFAIL-OPEN\t" in ln for ln in self.log_lines()), 2)

    def test_above_the_cap_the_refusal_lists_paths_instead(self):
        reason = self.assertDenied(self.decide(DISCIPLINE_RULE_GATE_MAX_INLINE="10"))
        self.assertIn(str(self.py_rule), reason)
        self.assertNotIn("RULE-SENTINEL-PY", reason)
        self.assertNotIn("rule-gate: inlined", reason)
        self.assertIn("Read each of these files whole", reason)

    def test_two_missing_rules_dedupe_and_both_inline(self):
        (self.rules / "test.md").write_text(TEST_RULE)
        (self.rules / "test-copy.md").write_text(TEST_RULE)
        target = str(self.proj / "src" / "test_x.py")
        reason = self.assertDenied(self.decide(self.hook_input(target)))
        self.assertIn("RULE-SENTINEL-PY", reason)
        self.assertEqual(reason.count("RULE-SENTINEL-TEST"), 1)


class PendingAndBreaker(GateCase):
    def test_a_sibling_within_the_window_gets_a_short_refusal(self):
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.decide()))
        short = self.assertDenied(self.decide(self.hook_input(str(self.proj / "src" / "c.py")),
                                              now=self.now + 30))
        self.assertNotIn("RULE-SENTINEL-PY", short)
        self.assertIn("sibling", short)
        self.assertIn(str(self.py_rule), short)
        self.assertIn("NEXT message", short)

    def test_the_transcript_counting_the_rule_clears_it_from_pending(self):
        tid = self.t.tool_use("Write", {"file_path": str(self.proj / "src" / "b.py")})
        self.t.denied(tid, self.assertDenied(self.decide()))
        self.assertAllowedSilently(self.decide(now=self.now + 500))
        state = json.loads(next(self.state.glob("*.json")).read_text())
        self.assertEqual(state["pending"], {})

    def test_blind_after_the_window_allows_logs_and_warns_then_never_refuses_again(self):
        self.assertDenied(self.decide())
        msg = self.assertAllowedWithWarning(self.decide(now=self.now + gate.SIBLING_WINDOW_S + 1))
        self.assertIn(str(self.py_rule), msg)
        self.assertEqual(sum("\tBLIND\t" in ln for ln in self.log_lines()), 1)
        again = self.assertAllowedWithWarning(self.decide(now=self.now + 10_000))
        self.assertIn(str(self.py_rule), again)
        self.assertEqual(sum("\tDENY\t" in ln for ln in self.log_lines()), 1)

    def test_a_pending_entry_from_before_a_compaction_is_inlined_again(self):
        """Refused, then compacted before the retry: stale, not blind, so the text goes again."""
        self.assertDenied(self.decide())
        self.t.boundary()
        self.t.summary("the rule said to add a canary")
        reason = self.assertDenied(self.decide(now=self.now + 500))
        self.assertIn("RULE-SENTINEL-PY", reason, "compaction dropped the text, so it is new again")
        self.assertEqual(sum("\tBLIND\t" in ln for ln in self.log_lines()), 0)

    def test_a_cleared_rule_dropped_by_compaction_is_inlined_again(self):
        tid = self.t.tool_use("Write", {"file_path": str(self.proj / "src" / "b.py")})
        self.t.denied(tid, self.assertDenied(self.decide()))
        self.assertAllowedSilently(self.decide(now=self.now + 1))
        self.t.boundary()
        reason = self.assertDenied(self.decide(now=self.now + 500))
        self.assertIn("RULE-SENTINEL-PY", reason)

    def test_state_is_per_session_and_agent(self):
        self.assertDenied(self.decide())
        other = self.hook_input()
        other["session_id"] = "another-session"
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.decide(other, now=self.now + 5)))

    def test_state_writes_are_atomic_and_old_files_are_pruned(self):
        self.state.mkdir()
        old = self.state / "stale.json"
        old.write_text("{}")
        os.utime(old, (time.time() - gate.STATE_TTL_S - 10,) * 2)
        self.assertDenied(self.decide())
        names = sorted(p.name for p in self.state.iterdir())
        self.assertEqual(len(names), 1, names)
        self.assertNotIn("stale.json", names)
        self.assertFalse([n for n in names if n.startswith(".tmp-")])
        self.assertIn(hashlib.sha256(PY_RULE.encode()).hexdigest(),
                      json.loads((self.state / names[0]).read_text())["pending"])

    def test_a_corrupt_state_file_is_read_as_empty(self):
        self.assertDenied(self.decide())
        next(self.state.glob("*.json")).write_text("not json")
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.decide(now=self.now + 5)))


class SameResponse(GateCase):
    """A result counts once the model has seen it, which is in its next response.

    Claude Code runs the calls of one response in turn and may write a refused call's result
    before a later call of the same response runs. That later call was generated without the
    rule, so the refusal's text on disk must not let it through. Measured live on 2.1.286: a
    Write, a five-second Bash and a Write in one response, and the second Write landed without
    the rule while the gate logged nothing.
    """

    def refuse(self, msg: str, target: str = "a.py") -> tuple[str, str]:
        """The gate refuses a Write as Claude Code would run it; the refusal goes on disk."""
        tid = "toolu_" + uuid.uuid4().hex[:24]
        d = self.hook_input(str(self.proj / "src" / target), tid=tid)
        reason = self.assertDenied(self.decide(d))
        self.t.tool_use("Write", d["tool_input"], msg_id=msg, tid=tid)
        self.t.denied(tid, reason)
        return tid, reason

    def test_a_later_call_of_the_same_response_is_refused_with_the_refusal_on_disk(self):
        msg = "msg_" + uuid.uuid4().hex[:24]
        self.refuse(msg)
        b = self.hook_input(str(self.proj / "src" / "b.py"))
        bash = self.t.tool_use("Bash", {"command": "sleep 5"}, msg_id=msg)
        self.t.tool_use("Write", b["tool_input"], msg_id=msg, tid=b["tool_use_id"])
        self.t.tool_result(bash, "", {"stdout": "", "stderr": "", "interrupted": False})
        short = self.assertDenied(self.decide(b, now=self.now + 6))
        self.assertIn("sibling", short)
        self.assertNotIn("RULE-SENTINEL-PY", short)
        self.t.denied(b["tool_use_id"], short)
        retry = self.hook_input(str(self.proj / "src" / "b.py"))
        self.assertAllowedSilently(self.decide(retry, now=self.now + 20))

    def test_the_current_call_not_yet_on_disk_behind_an_unanswered_call(self):
        """Its own entry is often not written yet; an unanswered call of the newest response
        on disk still places it there, since a new response waits for every result."""
        msg = "msg_" + uuid.uuid4().hex[:24]
        self.refuse(msg)
        self.t.tool_use("Bash", {"command": "sleep 5"}, msg_id=msg)
        self.assertIn("sibling", self.assertDenied(self.decide(now=self.now + 6)))

    def test_a_sibling_behind_a_long_tool_is_a_sibling_not_blind(self):
        msg = "msg_" + uuid.uuid4().hex[:24]
        self.refuse(msg)
        b = self.hook_input(str(self.proj / "src" / "b.py"))
        self.t.tool_use("Write", b["tool_input"], msg_id=msg, tid=b["tool_use_id"])
        self.assertIn("sibling", self.assertDenied(self.decide(b, now=self.now + 130)))
        self.assertEqual(sum("\tBLIND\t" in ln for ln in self.log_lines()), 0)

    def test_a_read_in_the_same_response_does_not_count(self):
        msg = "msg_" + uuid.uuid4().hex[:24]
        rid = self.t.tool_use("Read", {"file_path": str(self.py_rule)}, msg_id=msg)
        self.t.tool_result(rid, "1\t---", {"type": "text", "file": {
            "filePath": str(self.py_rule), "content": PY_RULE, "numLines": 7, "startLine": 1,
            "totalLines": 7}})
        b = self.hook_input()
        self.t.tool_use("Write", b["tool_input"], msg_id=msg, tid=b["tool_use_id"])
        reason = self.assertDenied(self.decide(b))
        self.assertIn("RULE-SENTINEL-PY", reason)
        self.t.denied(b["tool_use_id"], reason)
        lines, _ = gate.window_lines(str(self.tpath))
        self.assertNotIn(str(self.py_rule), gate.loaded_rules(lines, b["tool_use_id"]).paths)
        self.assertIn(str(self.py_rule), gate.loaded_rules(lines, "toolu_next").paths,
                      "negative control: a call of the next response has seen the Read")


class AnotherHooksRefusal(GateCase):
    """When two PreToolUse hooks refuse one call, Claude Code 2.1.286 keeps one reason, so the
    gate's text may never reach the transcript. That is neither a sibling nor a blind gate."""

    OTHER = "PreToolUse:Write hook error: other-hook: lint failed"

    def refused_by_both(self, now: float) -> str:
        d = self.hook_input()
        out = self.decide(d, now=now)
        self.t.tool_use("Write", d["tool_input"], tid=d["tool_use_id"])
        self.t.tool_result(d["tool_use_id"], self.OTHER, "Error: " + self.OTHER, is_error=True)
        return "" if out is None else json.dumps(out)

    def test_the_rule_is_given_again_then_the_breaker_opens(self):
        given = [self.refused_by_both(self.now + dt) for dt in (0, 30, 130)]
        for i, out in enumerate(given):
            self.assertIn("RULE-SENTINEL-PY", out, f"refusal {i + 1} must carry the full text, not "
                          "claim a sibling was given it")
        self.assertEqual([ln.split("\t")[1] for ln in self.log_lines()], ["DENY"] * 3)
        msg = self.assertAllowedWithWarning(self.decide(now=self.now + 200))
        self.assertIn(str(self.py_rule), msg)
        self.assertEqual(sum("\tBLIND\t" in ln for ln in self.log_lines()), 1)

    def test_a_sibling_of_a_call_whose_refusal_was_replaced_gets_the_text(self):
        msg = "msg_" + uuid.uuid4().hex[:24]
        a = self.hook_input(str(self.proj / "src" / "a.py"))
        self.assertDenied(self.decide(a))
        self.t.tool_use("Write", a["tool_input"], msg_id=msg, tid=a["tool_use_id"])
        self.t.tool_result(a["tool_use_id"], self.OTHER, "Error: " + self.OTHER, is_error=True)
        b = self.hook_input()
        self.t.tool_use("Write", b["tool_input"], msg_id=msg, tid=b["tool_use_id"])
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.decide(b, now=self.now + 1)))

    def test_its_own_text_on_disk_where_the_gate_does_not_read_is_blind_at_once(self):
        """A result shape the gate does not parse: the marker is on disk, but not in a field
        the gate reads. That is the blind case, and it is reported now rather than in 120 s."""
        d = self.hook_input()
        reason = self.assertDenied(self.decide(d))
        self.t.tool_use("Write", d["tool_input"], tid=d["tool_use_id"])
        self.t.write(self.t._base(type="user", message={"role": "user", "content": [
            {"type": "tool_result", "tool_use_id": d["tool_use_id"], "output": reason}]}))
        self.assertAllowedWithWarning(self.decide(now=self.now + 5))
        self.assertEqual(sum("\tBLIND\t" in ln for ln in self.log_lines()), 1)


# --- end to end ----------------------------------------------------------------------------------

# The PreToolUse entry `install.sh --refresh-rules` writes into a repository's own settings.json.
PROJECT_ENTRY = {"matcher": "Write|Edit|MultiEdit|NotebookEdit",
                 "hooks": [{"type": "command",
                            "command": 'python3 "$CLAUDE_PROJECT_DIR/.claude/hooks/rule_gate.py" '
                                       "|| true"}]}


class Deferral(GateCase):
    """A copy running from outside the project steps aside for the project's own wired copy.

    Wired at both levels, the two copies would each refuse the same write, so the user-level one
    (here, the gate loaded from the kit's reference/ directory, which is outside every temporary
    project) defers when the project's settings wire `.claude/hooks/rule_gate.py` for this tool
    and that file exists. The project's copy never defers. Each deferral has its negative control:
    a wiring the project copy could not act on must leave the user copy checking.
    """

    def vendor(self, settings_name="settings.json", entry=None, copy=True):
        hooks = self.proj / ".claude" / "hooks"
        hooks.mkdir(parents=True, exist_ok=True)
        if copy:
            (hooks / "rule_gate.py").write_bytes(GATE_PATH.read_bytes())
        (self.proj / ".claude" / settings_name).write_text(json.dumps(
            {"hooks": {"PreToolUse": [entry or PROJECT_ENTRY]}}, indent=2))
        return hooks / "rule_gate.py"

    def assertDeferred(self, out):
        """A silent allow, and exactly one DEFER line, the newest, naming the project copy."""
        self.assertAllowedSilently(out)
        lines = self.log_lines()
        self.assertEqual(sum("\tDEFER\t" in ln for ln in lines), 1, lines)
        self.assertIn("\tDEFER\t", lines[-1])
        self.assertIn(str(self.proj / ".claude" / "hooks" / "rule_gate.py"), lines[-1])

    def test_the_user_copy_defers_to_a_wired_project_copy(self):
        self.vendor()
        self.assertDeferred(self.decide())

    def test_settings_local_json_wiring_counts_too(self):
        self.vendor("settings.local.json")
        self.assertDeferred(self.decide())

    def test_wired_but_the_project_file_deleted_does_not_defer(self):
        self.vendor().unlink()
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.decide()))
        self.assertFalse(any("\tDEFER\t" in ln for ln in self.log_lines()))

    def test_no_wiring_does_not_defer(self):
        self.vendor()
        (self.proj / ".claude" / "settings.json").write_text('{"permissions": {}}\n')
        self.assertDenied(self.decide())

    def test_invalid_settings_json_does_not_defer(self):
        self.vendor()
        (self.proj / ".claude" / "settings.json").write_text('{"hooks": ')
        self.assertDenied(self.decide())

    def test_a_matcher_that_leaves_out_this_tool_does_not_defer(self):
        self.vendor(entry={**PROJECT_ENTRY, "matcher": "Edit"})
        self.assertDenied(self.decide())
        self.assertDeferred(self.decide(self.hook_input(tool="Edit")))

    def test_no_claude_project_dir_means_the_wired_command_cannot_resolve(self):
        self.vendor()
        env = dict(self.env)
        del env["CLAUDE_PROJECT_DIR"]
        self.assertDenied(gate.decide(self.hook_input(), env, self.now))

    def test_the_project_copy_never_defers(self):
        project_copy = self.vendor()
        full = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), **self.env}
        got = subprocess.run([sys.executable, str(project_copy)],
                             input=json.dumps(self.hook_input()), capture_output=True, text=True,
                             env=full, timeout=60)
        self.assertEqual(got.returncode, 0, got.stderr)
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(json.loads(got.stdout)))
        self.assertFalse(any("\tDEFER\t" in ln for ln in self.log_lines()))

    def run_copy(self, copy) -> dict:
        full = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), **self.env}
        got = subprocess.run([sys.executable, str(copy)], input=json.dumps(self.hook_input()),
                             capture_output=True, text=True, env=full, timeout=60)
        self.assertEqual(got.returncode, 0, got.stderr)
        return json.loads(got.stdout) if got.stdout.strip() else None

    def test_the_project_copy_through_a_symlinked_hooks_directory_never_defers(self):
        """With .claude/hooks linked out of the repository, the project copy resolves outside
        the root. Judged by resolved path, it took itself for a user-level copy and deferred to
        itself, and the user copy deferred to it: nothing checked the write."""
        outside = self.root / "outside-hooks"
        outside.mkdir()
        self.vendor()
        hooks = self.proj / ".claude" / "hooks"
        (outside / "rule_gate.py").write_bytes((hooks / "rule_gate.py").read_bytes())
        (hooks / "rule_gate.py").unlink()
        hooks.rmdir()
        hooks.symlink_to(outside, target_is_directory=True)
        self.assertIn("RULE-SENTINEL-PY", self.assertDenied(self.run_copy(hooks / "rule_gate.py")))
        self.assertFalse(any("\tDEFER\t" in ln for ln in self.log_lines()), self.log_lines())

    def test_a_command_that_only_mentions_the_path_does_not_defer(self):
        """The command must run this project's file, not merely contain its path."""
        for cmd in ("python3 /opt/old-checkout/.claude/hooks/rule_gate.py || true",
                    'python3 "$CLAUDE_PROJECT_DIR/.claude/hooks/rule_gate.py.orig" || true',
                    "echo .claude/hooks/rule_gate.py",
                    'python3 "$CLAUDE_PROJECT_DIR/other/.claude/hooks/rule_gate.py"'):
            with self.subTest(cmd=cmd):
                self.vendor(entry={**PROJECT_ENTRY, "hooks": [{"type": "command",
                                                                "command": cmd}]})
                self.assertDenied(self.decide())
                self.assertFalse(any("\tDEFER\t" in ln for ln in self.log_lines()))

    def test_each_spelling_that_runs_the_project_copy_defers(self):
        copy = self.proj / ".claude" / "hooks" / "rule_gate.py"
        for cmd in ('python3 "${CLAUDE_PROJECT_DIR}/.claude/hooks/rule_gate.py" || true',
                    "python3 .claude/hooks/rule_gate.py", "./.claude/hooks/rule_gate.py",
                    f"/usr/bin/python3 {copy}"):
            with self.subTest(cmd=cmd):
                if self.log.exists():
                    self.log.unlink()
                self.vendor(entry={**PROJECT_ENTRY, "hooks": [{"type": "command",
                                                                "command": cmd}]})
                self.assertDeferred(self.decide())

    def test_a_non_object_in_the_hooks_list_does_not_fail_open(self):
        """A stray string beside the real entry crashed the deferral, and the user copy then
        allowed every write in the project unchecked."""
        self.vendor(entry={**PROJECT_ENTRY, "hooks": ["x", *PROJECT_ENTRY["hooks"]]})
        self.assertDeferred(self.decide())
        self.assertFalse(any("\tFAIL-OPEN\t" in ln for ln in self.log_lines()))

    def test_a_write_no_rule_covers_logs_no_deferral(self):
        """The README says the gate writes nothing for a file outside the project; a DEFER line
        logged before the rules were looked at broke that."""
        self.vendor()
        self.assertAllowedSilently(self.decide(self.hook_input(str(self.root / "outside.py"))))
        self.assertEqual(self.log_lines(), [])

    def test_the_defer_line_says_the_write_was_not_checked_here(self):
        """Under --setting-sources without project, the project copy never runs while the user
        copy still defers to it, so DEFER must not read as "covered"."""
        self.vendor()
        self.assertDeferred(self.decide())
        self.assertIn("only if this session loads project hooks", self.log_lines()[-1])

    def test_the_user_copy_as_a_subprocess_prints_nothing(self):
        self.vendor()
        full = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), **self.env}
        got = subprocess.run([sys.executable, str(GATE_PATH)],
                             input=json.dumps(self.hook_input()), capture_output=True, text=True,
                             env=full, timeout=60)
        self.assertEqual((got.returncode, got.stdout), (0, ""), got.stderr)
        self.assertTrue(any("\tDEFER\t" in ln for ln in self.log_lines()))


class EndToEnd(GateCase):
    def run_hook(self, stdin: str, **env) -> subprocess.CompletedProcess:
        full = {"PATH": os.environ.get("PATH", "/usr/bin:/bin"), **self.env, **env}
        return subprocess.run([sys.executable, str(GATE_PATH)], input=stdin, capture_output=True,
                              text=True, env=full, timeout=60)

    def test_refusal_then_the_retry_allowed_once_the_refusal_is_in_the_transcript(self):
        write = self.hook_input()
        got = self.run_hook(json.dumps(write))
        self.assertEqual(got.returncode, 0, got.stderr)
        reason = self.assertDenied(json.loads(got.stdout))
        self.assertIn("RULE-SENTINEL-PY", reason)
        tid = self.t.tool_use("Write", write["tool_input"])
        self.t.denied(tid, reason)
        again = self.run_hook(json.dumps(self.hook_input()))
        self.assertEqual((again.returncode, again.stdout), (0, ""), again.stderr)

    def test_garbage_on_stdin_exits_zero_with_a_warning_and_a_log_line(self):
        got = self.run_hook("this is not json")
        self.assertEqual(got.returncode, 0, got.stderr)
        self.assertAllowedWithWarning(json.loads(got.stdout))
        self.assertTrue(any("\tFAIL-OPEN\t" in ln for ln in self.log_lines()))

    def test_an_internal_error_is_an_allow_with_a_warning(self):
        def boom(*_a, **_k):
            raise RuntimeError("planted")
        out = io.StringIO()
        with mock.patch.object(gate, "decide", boom), \
                mock.patch.object(sys, "stdin", io.StringIO(json.dumps(self.hook_input()))), \
                mock.patch.object(sys, "stdout", out), \
                mock.patch.dict(os.environ, self.env):
            self.assertEqual(gate.main(), 0)
        msg = self.assertAllowedWithWarning(json.loads(out.getvalue()))
        self.assertIn("internal error: RuntimeError: planted", msg)
        self.assertTrue(any("\tFAIL-OPEN\t" in ln and "planted" in ln for ln in self.log_lines()))

    def test_a_non_gated_tool_prints_nothing(self):
        d = self.hook_input()
        d["tool_name"] = "Bash"
        got = self.run_hook(json.dumps(d))
        self.assertEqual((got.returncode, got.stdout), (0, ""))


if __name__ == "__main__":
    started = time.time()
    result = unittest.main(exit=False, verbosity=1).result
    print(f"rule_gate_test: {result.testsRun} test(s), {len(result.failures)} failure(s), "
          f"{len(result.errors)} error(s), {len(result.skipped)} skipped "
          f"in {time.time() - started:.1f}s")
    sys.exit(0 if result.wasSuccessful() and not result.skipped else 1)
